services:
  # 1. Laravel Web Service
  - type: web
    name: forest-fire-web
    runtime: docker
    dockerfilePath: Dockerfile
    plan: free
    envVars:
      - key: APP_KEY
        generateValue: true
      - key: PYTHON_API_URL
        value: http://forest-fire-python:8000 # Internal URL

  # 2. Python Private Service
  - type: web
    name: forest-fire-python
    runtime: docker
    dockerfilePath: python.Dockerfile
    plan: free
    envVars:
      - key: PORT
        value: 8000